StockMarket/urls.py
from django.urls import path
from . import views

app_name = "StockMarket"

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('load-more', views.load_more, name='load-more'),
    path('<int:id>/<slug>/', views.stock_detail, name='stock_detail'),
    path('query/', views.query, name='query'),
    path('admin/query/<int:query_id>/',views.admin_query_detail, name='admin_query_detail')
]

Stock_Market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('StockMarket.urls', namespace='StockMarket')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StockMarket/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Stock_Name(models.Model):
    security_code = models.CharField(max_length=15)
    issuer_name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    security_id = models.CharField(max_length=50)
    security_name = models.CharField(max_length=250, db_index=True)
    status = models.BooleanField(default=True)
    group = models.CharField(max_length=5)
    face_value = models.IntegerField(default=0)
    isin_no = models.CharField(max_length=20)
    industry = models.CharField(max_length=100)
    instrument = models.CharField(max_length=15, default='Equity')
    video = models.FileField(upload_to="media/%Y", null=True)

    class Meta:
        ordering = ('security_code',)

    def __str__(self):
        return self.issuer_name

    def get_absolute_url(self):
        return reverse('StockMarket:stock_detail', args=[self.id, self.slug])


class Form_Query(models.Model):
    #Stock_Name = models.ForeignKey(Stock_Name, related_name='stock_name', on_delete=models.CASCADE)
    user_name = models.CharField(max_length=50)
    email = models.EmailField()
    enquery = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('user_name',)
    def __str__(self):
        return self.user_name


    def get_absolute_url(self):
        return reverse('StockMarket:index', args=[self.id])

StockMarket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Stock_Name
from django.core import serializers
from django.http import JsonResponse
from django.core.paginator import Paginator
from .models import Form_Query
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.

def signup(request):
    if request.method == 'GET':
        return render(request, 'StockMarket/signup.html', {'form': UserCreationForm})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('index')
            except IntegrityError:
                return render(request, 'StockMarket/signup.html',
                              {'form': UserCreationForm(), 'error': 'Password did not match'})


def login(request):
    if request.method == 'GET':
        return render(request, 'StockMarket/login.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'StockMarket/login.html',
                          {'form': AuthenticationForm(), 'error': 'Password did not match'})
        else:
            login(request, user)
            return redirect('index')


@login_required
def index(request, stock_slug=None):
    if 's' in request.GET:
        s = request.GET['s']
        stock_name = Stock_Name.objects.filter(issuer_name__icontains=s)
    else:
        stock_name = Stock_Name.objects.all()
    # pagination
    paginator = Paginator(stock_name, 5)
    page_number = request.GET.get('page')
    stock_name = paginator.get_page(page_number)
    return render(request, 'StockMarket/index.html', {'stock_name': stock_name, 'form':query })

def stock_detail(request, id, slug):
    stock_name = get_object_or_404(Stock_Name,
                                   id=id,
                                   slug=slug,
                                   status=True)
    return render(request, 'StockMarket/detail.html', {'stock_name': stock_name})


def query(request):
    if request.method == "POST":
        name = request.POST['user_name']
        email = request.POST['email']
        query = request.POST['query']

        newenqury = Form_Query(user_name=name, email=email, enquery=query)
        newenqury.save()
    return render(request, 'StockMarket/query.html')

# Load More
def load_more(request):
    offset = int(request.POST['offset'])
    limit = 5
    stock_list = Stock_Name.objects.all()[offset:limit + offset]
    totalData = Stock_Name.objects.count()
    data = {}
    stock_list_json = serializers.serialize('json', stock_list)
    return JsonResponse(data={
        'stock_list': stock_list_json,
        'totalResult': totalData,
    })

@staff_member_required
def admin_query_detail(request, query_id):
    query = get_object_or_404(Form_Query, id=query_id)
    return render(request, 'admin/StockMarket/form_query/.html', {'query': query})
#alok

StockMarket/templates/StockMarket/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <script src={% static '' %}></script>
    <title>Stock Market List</title>
</head>
<body>
{% if user.is_authenticate %}
    <h2>Welcome : {{ user.username }}</h2>
{% else %}
    <button><a href="{% url 'StockMarket:signup' %}">Sign up</a></button>
<button><a href="{% url 'StockMarket:login' %}">Login</a></button>
<button><a href="{% url 'StockMarket:index' %}">Home</a></button>
{% endif %}

{% block content %}
{% endblock %}
</body>
</html>

StockMarket/templates/StockMarket/detail.html
{% extends 'StockMarket/base.html' %}
{% block content%}
    <h3>{{ stock_name.issuer_name }}</h3>
    <video width="320" height="240" controls>
  <source src="{{ stock_name.video.url }}" type="video/mp4">
</video>
    <h4>Stock Details</h4>
    <p>Security Code: {{ stock_name.security_code }}, Issuer Name: {{ stock_name.issuer_name  }}, Security Id: {{ stock_name.security_id }}<br>
    Status: {{ stock_name.status }}, Group: {{ stock_name.group }}, Face Value: {{ stock_name.face_value }},<br>
        ISIN No: {{ stock_name.isin_no }}, Industry: {{ stock_name.industry }}, Instrument: {{ stock_name.instrument }}</p>
{% endblock %}

StockMarket/templates/StockMarket/index.html
{% extends 'StockMarket/base.html' %}
{% load static %}
{% block content%}
<div class="container my-4 post-wrapper">
        <!-- Search Start -->
        <div class="jumbotron border shadow">
            <div class="row">
                <div class="col-md-8 offset-2">
                    <form>
                        <div class="input-group">
                            <input name="s" type="text" placeholder="Search" class="form-control form-control-lg" />
                            <div class="input-group-append">
                                <button class="btn btn-dark btn-lg">Search</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- End Search -->

        <h3>All Stocks</h3>
        {% for stockname in stock_name %}
        <div class="card my-3 sm">
            <h5 class="card-header">
                <a href="{{ stockname.get_absolute_url }}">{{ stockname.issuer_name }}</a>
                <a href="{% url 'StockMarket:query' %}">query</a>
            </h5>
        </div>
        {% endfor %}


</div>
    <p class="text-center">
        <button class="btn btn-dark" id="loadmoreBtn">Load More</button>
    </p>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function(){
        $("#loadmoreBtn").on('click',function(){
            var _currentResult=$(".sm").length;
            // Run Ajax
            $.ajax({
                url:"{% url 'StockMarket:load-more' %}",
                type:'post',
                data:{
                    'offset':_currentResult,
                    'csrfmiddlewaretoken':"{{csrf_token}}"
                },
                dataType:'json',
                beforeSend:function(){
                    $("#loadmoreBtn").addClass('disabled').text('Loading..');
                },
                success:function(res){
                    var _html='';
                    var json_data=$.parseJSON(res.stock_list);
                    $.each(json_data,function(index,data){
                        _html+='<div class="card my-3 sm">\
            <h5 class="card-header"><a href="{{ stockname.get_absolute_url }}">'+data.fields.issuer_name+'</a>\
            <a href="{% url 'StockMarket:query' %}">query</a>\
            </h5>\
        </div>';
                    });
                    $(".post-wrapper").append(_html);
                    var _countTotal=$(".sm").length;
                    if(_countTotal==res.totalResult){
                        $("#loadmoreBtn").remove();
                    }else{
                        $("#loadmoreBtn").removeClass('disabled').text('Load More');
                    }
                }
            });
        });
    });
</script>
    <script>
function openForm() {
  document.getElementById("query_form").style.display = "block";
}

function closeForm() {
  document.getElementById("query_form").style.display = "none";
}
</script>

{% endblock %}

StockMarket/templates/StockMarket/login.html
{% extends 'StockMarket/base.html' %}
{% block content%}
<h1>Login</h1>
<h2>{{ error }}</h2>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Login</button>
</form>
{% endblock %}

StockMarket/templates/StockMarket/query.html
{% extends 'StockMarket/base.html' %}
{% block content %}
<form action="" method="post" class="form-horizontal contactForm" role="form">
            {% csrf_token %}
            <div class="col-md-offset-2 col-md-8">
              <div class="form-group">
                <input type="text" name="stock_name" class="form-control" id="stock_name" placeholder="Stock Name" />
                <div class="validation"></div>
              </div>
            </div>

            <div class="col-md-offset-2 col-md-8">
              <div class="form-group">
                <input type="text" class="form-control" name="user_name" id="user_name" placeholder="Your Name" />
                <div class="validation"></div>
              </div>
            </div>
            <div class="col-md-offset-2 col-md-8">
              <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="Email" />
                <div class="validation"></div>
              </div>
            </div>

            <div class="col-md-offset-2 col-md-8">
              <div class="form-group">
                <textarea class="form-control" name="query" rows="5" data-rule="required"  placeholder="Ask your queries"></textarea>
                <div class="validation"></div>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-offset-2 col-md-8">
                <button type="submit" class="btn btn-theme btn-lg btn-block">Send message</button>
              </div>
            </div>
          </form>
{% endblock %}

StockMarket/templates/StockMarket/signup.html
{% extends 'StockMarket/base.html' %}
{% block content%}
<h1>Sign Up</h1>
<h2>{{ error }}</h2>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="submit">
</form>
{% endblock %}